/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;
import Clases.Cliente;
import Clases.Empleado;
import Clases.Hash;
import Clases.Persona;
import Clases.Usuarios;
import JPAController.EmpleadoJpaController;
import JPAController.PersonaJpaController;
import JPAController.UsuariosJpaController;
import com.sun.glass.events.KeyEvent;
import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author Kur013
 */
public class IniciodeSesion extends javax.swing.JFrame {

    /**
     * Creates new form IniciodeSesion
     */
    
    private Component confirm;
    EntityManagerFactory emf =Persistence.createEntityManagerFactory("CarSoft");
      UsuariosJpaController  usuarioDao = new UsuariosJpaController(emf);
      PersonaJpaController personaDao= new PersonaJpaController(emf);
      EmpleadoJpaController empleadoDao = new EmpleadoJpaController(emf);
      private String user, password;
      
    public IniciodeSesion() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Img/CarSoft-removebg-preview.png")).getImage());
         txt_usuario.setFocusable(true);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.btnIngresar.setBackground( new Color(14, 209, 69));
        this.btnSalir.setBackground( new Color(236, 28, 36));
        labelEmple1.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_password = new javax.swing.JPasswordField();
        txt_usuario = new javax.swing.JTextField();
        labelEmple1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_passwordActionPerformed(evt);
            }
        });
        btn_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn_passwordKeyTyped(evt);
            }
        });
        getContentPane().add(btn_password);
        btn_password.setBounds(670, 420, 130, 30);

        txt_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_usuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txt_usuario);
        txt_usuario.setBounds(670, 380, 130, 30);

        labelEmple1.setText("jLabel5");
        getContentPane().add(labelEmple1);
        labelEmple1.setBounds(140, 130, 340, 14);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(570, 390, 90, 14);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(570, 430, 90, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\CarSoft-Version-2.1\\src\\main\\resources\\Img\\CarSoft-removebg-preview.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(600, 10, 200, 190);

        btnIngresar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnIngresar.setIcon(new javax.swing.ImageIcon("C:\\CarSoft-Version-2.1\\src\\main\\resources\\Img\\Ingresar.png")); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar);
        btnIngresar.setBounds(640, 500, 170, 59);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Inicio de Sesión");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(650, 320, 108, 17);

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon("C:\\CarSoft-Version-2.1\\src\\main\\resources\\Img\\Salir.png")); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(1233, 20, 110, 41);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\CarSoft-Version-2.1\\src\\main\\resources\\Img\\Fondo.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-10, -30, 1750, 1130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_passwordActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
         System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        InicioSesion();
       
    }//GEN-LAST:event_btnIngresarActionPerformed
public boolean InicioSesion(){
     if (txt_usuario.getText().equals("") && btn_password.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Usuario y contraseña estan vacios\nIngrese su usuario y contraseña","Error!", JOptionPane.ERROR_MESSAGE);
            //txt_usuario.setFocusable(true);
            return false;
       }
       else{
           
       }
       if (txt_usuario.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Usuario esta vacio\nIngrese su usuario","Error!", JOptionPane.ERROR_MESSAGE);
            //txt_usuario.setFocusable(true);
            return false;
       }
       else{
           
       }
       if (btn_password.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Contraseña esta vacio\nIngrese su contraseña","Error!", JOptionPane.ERROR_MESSAGE);
            btn_password.setFocusable(true);
            return false;
        }
       java.util.List<Usuarios> temp;
       temp = usuarioDao.findUsuariosEntities();
       for(Usuarios u : temp){
       if(u.getId_Nombre().equals(txt_usuario.getText())){
            u= usuarioDao.findUsuarios(u.getId_Usuario());
            if(u.isEstado()!=true){
            JOptionPane.showMessageDialog(null,"Este usuario esta bloqueado, por favor comunicarse con el Gerente","Información", JOptionPane.INFORMATION_MESSAGE); 
            return false;
        }
       }
       }
        boolean flag = false;
        boolean flag2 = false;
        boolean flag3 = false;
        for(Usuarios u : temp){
            if(u.getId_Nombre().equals(txt_usuario.getText())){
                flag=true;
                if(u.getContraseña().equals(Hash.getHash(btn_password.getText()))){
                    flag2=true;
                    if(u.isEstado()){
                        flag3=true;
                    }                   
                }   
            }
        }
        if(flag && flag2 && flag3){
            FrmMenu menu = new FrmMenu();
            menu.setVisible(true);
            
            Empleado temp2 = new Empleado();
            Persona temp3 = new Persona();
            for(Usuarios u : temp){
                if(u.getId_Nombre().equals(txt_usuario.getText())){
                    temp2=empleadoDao.findEmpleado(u.getId_Empleado());
                    temp3=personaDao.findPersona(temp2.getId_Persona());
                    u.setIntentos(0);
        try {
                     usuarioDao.edit(u);
        } catch (Exception ex) {
            Logger.getLogger(FrmPieza.class.getName()).log(Level.SEVERE, null, ex);
        }
                }
            }   
            FrmMenu.txtBienvenido.setText("Bienvenido "+temp3.getNombre()+" "+temp3.getApellido());
            FrmMenu.lIDEmpleado.setText(String.valueOf(temp2.getId_Empleado()));
            FrmMenu.labelEmple1.setText(temp3.getNombre()+" "+temp3.getApellido());
            this.dispose();
            
        }
        else if (flag && !flag2){
            
            
            
            
            for(Usuarios u : temp){
            if(u.getId_Nombre().equals(txt_usuario.getText())){
            u= usuarioDao.findUsuarios(u.getId_Usuario());
            int aux= u.getIntentos()+1;
            u.setIntentos(aux); 
            
                if(u.getIntentos()>=3){
                //JOptionPane.showMessageDialog(null, "Esta cuenta ha sido bloqueada por intentar acceder sin exito 3 veces","Error!", JOptionPane.ERROR_MESSAGE);
                 u.setEstado(false); 
                 return false;
                }
                if(u.getIntentos()<=2){
                //JOptionPane.showMessageDialog(this, "La contraseña no es valida\n Ingrese su contraseña","Contraseña Incorrecta", JOptionPane.ERROR_MESSAGE);
                 btn_password.setFocusable(true);  
                 return false;
                }
            try {
            usuarioDao.edit(u);
            } catch (Exception ex) {
            Logger.getLogger(IniciodeSesion.class.getName()).log(Level.SEVERE, null, ex);
            }       
            }
             
            }
            }
        else if (flag && flag2 && !flag3){
            //JOptionPane.showMessageDialog(this,"Cuenta inactiva, pongase en contacto con el Gerente o departamento de TI","Error!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        else if(!flag){
            if("root".equals(txt_usuario.getText())){
                if("admin".equals(btn_password.getText())){
                    FrmMenu menu = new FrmMenu();
                    menu.setVisible(true);
                    this.setVisible(false);
                }
            }
            else{
            //JOptionPane.showMessageDialog(this, "Usuario no encontrado en el sistema, Asegurese que su Usuario este escrito correctamente","Error!", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        return true;
}
    private void txt_usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usuarioKeyTyped
                char c = evt.getKeyChar();
        if((c < 'a' || c > 'z') && (c != '.')&&(c < '0' || c > '9')&& (c < 'A' || c > 'Z'&& c != 'Ñ' && c != 'ñ' && c != 'Á' && c != 'É' && c != 'Í' && c != 'Ó' && c != 'Ú' && c != 'á' && c != 'é' && c != 'í' && c != 'ó' && c != 'ú')){

            evt.consume();

        }
              
        if (txt_usuario.getText().length() >= 15){
        
        evt.consume();
        
        }
        
    }//GEN-LAST:event_txt_usuarioKeyTyped

    private void btn_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_passwordKeyTyped
       char c = evt.getKeyChar();
        if((c < 'a' || c > 'z') && (c != '@'&& c != '#' && c != '$' && c != '%' &&c != '^' && c != '&' && c != '+' && c != '=' )&&(c < '0' || c > '9')&& (c < 'A' || c > 'Z'&& c != 'Ñ' && c != 'ñ' && c != 'Á' && c != 'É' && c != 'Í' && c != 'Ó' && c != 'Ú' && c != 'á' && c != 'é' && c != 'í' && c != 'ó' && c != 'ú') ){

            evt.consume();

        }
        if (btn_password.getText().length() >= 15){
        
        evt.consume();
        
        }
    }//GEN-LAST:event_btn_passwordKeyTyped

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    public javax.swing.JPasswordField btn_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel labelEmple1;
    public javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
